-- ============================================================
-- seed_pruebas.sql — Clientes y flows de prueba
-- Ejecutar desde el servidor con:
--   docker exec -i pg-integrador psql -U integrador -d integrador < seed_pruebas.sql
-- Requiere: schema.sql ejecutado previamente (users id=1 existe)
-- ============================================================

-- Limpieza (orden por FK)
DELETE FROM executions WHERE flow_id IN (SELECT id FROM flows WHERE client_id IN (SELECT id FROM clients WHERE client_id IN ('pruebaws','pruebackt','pruebasap','pruebaexcel')));
DELETE FROM flows WHERE client_id IN (SELECT id FROM clients WHERE client_id IN ('pruebaws','pruebackt','pruebasap','pruebaexcel'));
DELETE FROM clients WHERE client_id IN ('pruebaws','pruebackt','pruebasap','pruebaexcel');

-- ============================================================
-- CLIENTES DE PRUEBA
-- ============================================================
INSERT INTO clients (client_id, name, erp_type, created_by) VALUES
    ('pruebaws',    'Prueba SIESA WS',  'ws',       1),
    ('pruebackt',   'Prueba Connekta',  'connekta', 1),
    ('pruebasap',   'Prueba SAP B1',    'sap',      1),
    ('pruebaexcel', 'Prueba Excel',     'excel',    1);

-- ============================================================
-- FLOWS — PRUEBAWS (7 flows: 2 maestros + 2 compras + 2 ventas + 1 factura)
-- ============================================================

-- items (execution_order=1)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebaws'), 'items', 'items', '{"sql": "SET QUOTED_IDENTIFIER OFF; SELECT TOP 50 ISNULL(f120_id, \"\") AS referencia, REPLACE(ISNULL(f120_descripcion, \"SIN DESCRIPCION\"), CHAR(39), \"\") AS descripcion, ISNULL((SELECT TOP 1 b.f131_id FROM t131_mc_items_barras b WHERE b.f131_rowid_item_ext = f121_rowid ORDER BY b.f131_ts DESC), \"\") AS codigo_barras, ISNULL(TRIM(f120_id_unidad_inventario), \"UNID\") AS unidad, ISNULL(CAST(f122_peso AS VARCHAR(12)), \"0\") AS peso, CAST(ISNULL(f122_volumen, \"0\") AS VARCHAR(10)) AS volumen, \"0\" AS costo, 0 AS precio, 0 AS iva, CASE f120_ind_lote WHEN 1 THEN \"lot\" WHEN 2 THEN \"lot\" ELSE \"none\" END AS tracking, ISNULL(f120_vida_util, 0) AS vence, ISNULL(TRIM(t_cat.f106_descripcion), \"\") AS categoria FROM t120_mc_items LEFT JOIN t121_mc_items_extensiones ON (f121_rowid_item = f120_rowid AND f121_id_cia = f120_id_cia) LEFT JOIN t122_mc_items_unidades ON (f120_rowid = f122_rowid_item AND f122_id_unidad = f120_id_unidad_inventario) LEFT JOIN t125_mc_items_criterios AS t_cat_link ON (f120_rowid = t_cat_link.f125_rowid_item AND t_cat_link.f125_id_plan = \"001\") LEFT JOIN t106_mc_criterios_item_mayores AS t_cat ON (t_cat_link.f125_id_criterio_mayor = t_cat.f106_id AND t_cat_link.f125_id_plan = t_cat.f106_id_plan AND t_cat_link.f125_id_cia = t_cat.f106_id_cia) WHERE f120_id_cia = 1 ORDER BY f120_id ASC; SET QUOTED_IDENTIFIER ON;", "uom_mapping": {"UND": "Unidades", "und": "Unidades", "UNID": "Unidades", "KG": "kg", "kgs": "kg", "LT": "lt"}, "resolve_sql_inject": "AND f120_id IN ({refs}) "}'::jsonb, NULL, true, 1, 1);

-- customer (execution_order=2)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebaws'), 'partners', 'customer', '{"sql": "SET QUOTED_IDENTIFIER OFF; SELECT DISTINCT TOP 50 TRIM(f200_nit) AS identificacion, f201_id_sucursal AS sucursal, CONCAT(f200_razon_social, \" - \", f201_id_sucursal) AS nombre, TRIM(f015_email) AS email, TRIM(f015_telefono) AS telefono, TRIM(f015_direccion1) AS direccion, TRIM(f015_cod_postal) AS codigo_postal, TRIM(f013_descripcion) AS ciudad, TRIM(f012_descripcion) AS departamento, TRIM(f011_descripcion) AS pais FROM t201_mm_clientes INNER JOIN t200_mm_terceros ON (f200_rowid = f201_rowid_tercero AND f200_id_cia = f201_id_cia AND f200_ind_estado = 1) INNER JOIN t015_mm_contactos ON (f201_rowid_contacto = f015_rowid AND f201_id_cia = f015_id_cia) INNER JOIN t011_mm_paises ON (f011_id = f015_id_pais) INNER JOIN t012_mm_deptos ON (f012_id_pais = f015_id_pais AND f012_id = f015_id_depto) INNER JOIN t013_mm_ciudades ON (f013_id_pais = f015_id_pais AND f013_id_depto = f015_id_depto AND f013_id = f015_id_ciudad) WHERE f201_id_cia = 1 ORDER BY 1 ASC; SET QUOTED_IDENTIFIER ON;", "sucursal_hierarchy": false, "country_id": 49, "identification_type_id": 5, "resolve_sql_inject": "AND TRIM(f200_nit) IN ({refs}) "}'::jsonb, NULL, true, 2, 1);

-- supplier (execution_order=3)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebaws'), 'partners', 'supplier', '{"sql": "SET QUOTED_IDENTIFIER OFF; SELECT TOP 50 TRIM(f200_nit) AS identificacion, f202_id_sucursal AS sucursal, CONCAT(f200_razon_social, \" - \", f202_id_sucursal) AS nombre, TRIM(f015_email) AS email, TRIM(f015_telefono) AS telefono, TRIM(f015_direccion1) AS direccion, TRIM(f015_cod_postal) AS codigo_postal, TRIM(f013_descripcion) AS ciudad, TRIM(f012_descripcion) AS departamento, TRIM(f011_descripcion) AS pais FROM t202_mm_proveedores INNER JOIN t200_mm_terceros ON (f200_rowid = f202_rowid_tercero AND f200_id_cia = f202_id_cia AND f200_ind_estado = 1) INNER JOIN t015_mm_contactos ON (f202_rowid_contacto = f015_rowid AND f202_id_cia = f015_id_cia) INNER JOIN t011_mm_paises ON (f011_id = f015_id_pais) INNER JOIN t012_mm_deptos ON (f012_id_pais = f015_id_pais AND f012_id = f015_id_depto) INNER JOIN t013_mm_ciudades ON (f013_id_pais = f015_id_pais AND f013_id_depto = f015_id_depto AND f013_id = f015_id_ciudad) WHERE f202_id_cia = 1 ORDER BY 1 ASC; SET QUOTED_IDENTIFIER ON;", "country_id": 49, "identification_type_id": 5, "resolve_sql_inject": "AND TRIM(f200_nit) IN ({refs}) "}'::jsonb, NULL, true, 3, 1);

-- compras (execution_order=10)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebaws'), 'compras', 'purchases', '{"sql": "SET QUOTED_IDENTIFIER OFF; SELECT TOP 10 CONCAT(TRIM(f420_id_tipo_docto), f420_id_co, \"-\", f420_consec_docto) AS compra, TRIM(tercero.f200_nit) AS proveedor, TRIM(f202_id_sucursal) AS sucursal_proveedor, \"\" AS referencia_compra, CONVERT(VARCHAR, f420_fecha_ts_creacion, 23) AS fecha_entrega, \"draft\" AS estado, 1 AS almacen, f120_id AS producto, CAST(f421_precio_unitario AS DECIMAL(18, 2)) AS precio_unitario, CAST(f421_cant_pedida AS INTEGER) AS cantidad, ISNULL(CAST(f423_tasa AS DECIMAL(12,2)), 19) AS impuesto, f150_id AS bodega_siesa FROM t420_cm_oc_docto INNER JOIN t202_mm_proveedores ON (f420_rowid_tercero_facturar = f202_rowid_tercero AND f420_id_sucursal_facturar = f202_id_sucursal AND f420_id_cia = f202_id_cia) INNER JOIN t200_mm_terceros AS tercero ON (f420_rowid_tercero_facturar = tercero.f200_rowid AND tercero.f200_rowid = f202_rowid_tercero AND tercero.f200_id_cia = f202_id_cia) INNER JOIN t421_cm_oc_movto ON (f421_rowid_oc_docto = f420_rowid AND f421_id_cia = f420_id_cia) INNER JOIN t121_mc_items_extensiones ON (f121_rowid = f421_rowid_item_ext AND f121_id_cia = f421_id_cia) INNER JOIN t120_mc_items ON (f120_rowid = f121_rowid_item AND f120_id_cia = f121_id_cia) INNER JOIN t150_mc_bodegas ON (f421_rowid_bodega = f150_rowid) LEFT JOIN t423_cm_oc_movto_imp ON (f423_rowid_oc_movto = f421_rowid AND f423_id_cia = f421_id_cia AND f423_id_llave_impuesto_desc IS NOT NULL) WHERE f420_id_cia = 1 AND f420_ind_estado IN (\"1\", \"2\") ORDER BY f420_consec_docto DESC; SET QUOTED_IDENTIFIER ON;", "warehouse_mapping": {}}'::jsonb, NULL, true, 10, 1);

-- transferencia_entrada (execution_order=11)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebaws'), 'transferencia_entrada', 'purchases', '{"sql": "SET QUOTED_IDENTIFIER OFF; SELECT TOP 10 CONCAT(TRIM(T350.f350_id_tipo_docto), TRIM(T350.f350_id_co), \"-\", T350.f350_consec_docto) AS compra, \"123456789\" AS proveedor, \"001\" AS sucursal_proveedor, \"\" AS referencia_compra, ISNULL(CONVERT(VARCHAR, t350.f350_fecha, 23), \"\") AS fecha_entrega, \"draft\" AS estado, 1 AS almacen, T120.f120_id AS producto, 0 AS precio_unitario, T470.f470_cant_base AS cantidad, 0 AS impuesto, \"\" AS bodega_siesa FROM t350_co_docto_contable T350 INNER JOIN t450_cm_docto_invent T450 ON T350.f350_rowid = T450.f450_rowid_docto INNER JOIN t150_mc_bodegas T150E ON T150E.f150_rowid = T450.f450_rowid_bodega_entrada INNER JOIN t470_cm_movto_invent T470 ON T470.f470_rowid_docto = T350.f350_rowid INNER JOIN t121_mc_items_extensiones T121 ON T121.f121_rowid = T470.f470_rowid_item_ext INNER JOIN t120_mc_items T120 ON T120.f120_rowid = T121.f121_rowid_item WHERE t350.f350_id_tipo_docto = \"TM\" AND T350.f350_id_cia = 1 AND T350.f350_fecha_ts_creacion > CONVERT(VARCHAR, DATEADD(day, -30, GETDATE()), 23) ORDER BY T350.f350_fecha_ts_creacion DESC; SET QUOTED_IDENTIFIER ON;", "warehouse_mapping": {}}'::jsonb, NULL, true, 11, 1);

-- ventas (execution_order=12)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebaws'), 'ventas', 'sales', '{"sql": "SET QUOTED_IDENTIFIER OFF; SELECT TOP 10 CONCAT(TRIM(t430.f430_id_co), TRIM(t430.f430_id_tipo_docto), t430.f430_consec_docto) AS pedido, TRIM(t200.f200_nit) AS cliente, TRIM(t201.f201_id_sucursal) AS sucursal_cliente, ISNULL(CONVERT(VARCHAR, t430.f430_id_fecha, 23), \"\") AS fecha_pedido, \"draft\" AS estado, 1 AS almacen, TRIM(RTRIM(v121.v121_id_item)) AS producto, t431.f431_cant1_pedida AS cantidad_pedida, t431.f431_precio_unitario_base AS precio_unitario, \"\" AS impuesto, \"\" AS zona, \"\" AS vendedor, \"\" AS condicion_pago, TRIM(t430.f430_notas) AS observacion, TRIM(t431.f431_id_unidad_medida) AS unidad_medida, TRIM(t150.f150_id) AS bodega_siesa FROM t201_mm_clientes t201 INNER JOIN t200_mm_terceros t200 ON t201.f201_rowid_tercero = t200.f200_rowid AND t201.f201_id_cia = t200.f200_id_cia INNER JOIN t430_cm_pv_docto t430 ON t200.f200_id_cia = t430.f430_id_cia AND t200.f200_rowid = t430.f430_rowid_tercero_fact AND t201.f201_id_sucursal = t430.f430_id_sucursal_fact INNER JOIN t431_cm_pv_movto t431 ON t431.f431_rowid_pv_docto = t430.f430_rowid AND t430.f430_id_cia = t431.f431_id_cia INNER JOIN t150_mc_bodegas t150 ON t150.f150_rowid = t431.f431_rowid_bodega INNER JOIN v121 ON v121.v121_id_cia = t431.f431_id_cia AND t431.f431_rowid_item_ext = v121.v121_rowid_item_ext WHERE t430.f430_id_cia = 1 AND t430.f430_ind_estado = 2 ORDER BY 1 DESC; SET QUOTED_IDENTIFIER ON;", "warehouse_mapping": {}}'::jsonb, NULL, true, 12, 1);

-- facturas (execution_order=13)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebaws'), 'facturas', 'sales', '{"sql": "SET QUOTED_IDENTIFIER OFF; SELECT TOP 10 CONCAT(TRIM(f350_id_tipo_docto), f350_id_co, \"-\", f350_consec_docto) AS pedido, LTRIM(RTRIM(cliente.f200_nit)) AS cliente, LTRIM(RTRIM(f201_id_sucursal)) AS sucursal_cliente, CONVERT(varchar, f350_fecha, 23) AS fecha_pedido, \"draft\" AS estado, 1 AS almacen, LTRIM(RTRIM(f120_id)) AS producto, CAST(f470_cant_1 AS INTEGER) AS cantidad_pedida, CAST(f470_precio_uni AS DECIMAL(18, 2)) AS precio_unitario, \"\" AS impuesto, \"\" AS zona, \"\" AS vendedor, LTRIM(RTRIM(f461_id_cond_pago)) AS condicion_pago, \"\" AS observacion, f470_id_unidad_medida AS unidad_medida, TRIM(f150_id) AS bodega_siesa FROM t350_co_docto_contable INNER JOIN t461_cm_docto_factura_venta ON (f461_rowid_docto = f350_rowid) INNER JOIN t470_cm_movto_invent ON (f470_rowid_docto_fact = f461_rowid_docto) INNER JOIN t200_mm_terceros AS cliente ON (f461_rowid_tercero_fact = f200_rowid) INNER JOIN t201_mm_clientes ON (cliente.f200_rowid = f201_rowid_tercero AND f201_id_sucursal = f461_id_sucursal_fact) INNER JOIN t121_mc_items_extensiones ON (f470_rowid_item_ext = f121_rowid) INNER JOIN t120_mc_items ON (f121_rowid_item = f120_rowid) INNER JOIN t150_mc_bodegas ON (f470_rowid_bodega = f150_rowid) WHERE f350_id_tipo_docto IN (\"FAC\", \"FPZ\") AND f350_id_cia = 1 ORDER BY f350_consec_docto DESC; SET QUOTED_IDENTIFIER ON;", "warehouse_mapping": {}}'::jsonb, NULL, true, 13, 1);

-- ============================================================
-- FLOWS — PRUEBACKT (9 flows)
-- ============================================================

-- items (execution_order=1)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebackt'), 'items', 'items', '{"query_desc": "pinturastitopabon_producto_wms", "parametros": "FechaInicio = 20260101|FechaFin = 20261231", "paginacion": false, "mapping": {"Referencia_Item": "referencia", "name": "descripcion", "barcode": "codigo_barras", "unidad_venta": "unidad", "descripcion_inv_serv": "categoria", "vida_util": "vence"}, "hardcodes": {"impuesto": 19.0}, "conditionals": [{"tipo": "reglas", "campo_destino": "tracking", "campo_origen": "Maneja_lote", "reglas": [{"si": "SI", "entonces": "lot"}], "default": "none"}, {"tipo": "reglas", "campo_destino": "use_expiration_date", "campo_origen": "Caducidad", "reglas": [{"si": "SI", "entonces": 1}], "default": 0}, {"tipo": "funcion", "campo_destino": "ruta", "funcion": "route_compra_manufactura_prefijo", "params": {"campo_compra": "Compra", "campo_manufactura": "Manufactura", "campo_referencia": "Referencia_Item", "prefijo_manufactura": "PT"}}], "uom_mapping": {"UND": "Unidades", "und": "Unidades", "UNID": "Unidades", "KG": "kg", "kgs": "kg", "LT": "lt", "GAL": "Galones"}}'::jsonb, NULL, true, 1, 1);

-- customer (execution_order=2)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebackt'), 'partners', 'customer', '{"query_desc": "pinturastitopabon_Clientes", "parametros": "fecha_inicio = 20260101|fecha_fin = 20261231", "paginacion": false, "mapping": {"vat": "identificacion", "nombre_completo": "nombre", "correo": "email"}, "hardcodes": {}, "conditionals": [], "sucursal_hierarchy": true, "sucursal_padre": "001", "country_id": 49, "identification_type_id": 5}'::jsonb, NULL, true, 2, 1);

-- supplier (execution_order=3)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebackt'), 'partners', 'supplier', '{"query_desc": "pinturastitopabon_Proveedores", "parametros": "fecha_inicio = 20260101|fecha_fin = 20261231", "paginacion": false, "mapping": {"vat": "identificacion", "nombre_completo": "nombre", "correo": "email"}, "hardcodes": {}, "conditionals": [], "country_id": 49, "identification_type_id": 5}'::jsonb, NULL, true, 3, 1);

-- compras (execution_order=10)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebackt'), 'compras', 'purchases', '{"query_desc": "pinturastitopabon_OrdenDeCompra", "parametros": "fecha_inicio = 20260101|fecha_fin = 20261231", "paginacion": false, "mapping": {"documento": "compra", "id_tercero": "proveedor", "id_sucursal_prov": "sucursal_proveedor", "consec_docto": "referencia_compra", "Referencia": "producto", "Cant_pendiente": "cantidad", "Precio_unit": "precio_unitario", "Desc_bodega": "bodega_siesa", "id_tercero_comprador": "comprador", "Fecha_entrega": "fecha_entrega"}, "hardcodes": {"estado": "draft", "impuesto": 19.0, "almacen": 1}, "conditionals": [], "warehouse_mapping": {}}'::jsonb, NULL, true, 10, 1);

-- ventas (execution_order=11)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebackt'), 'ventas', 'sales', '{"query_desc": "pinturastitopabon_pedidospuntodeventa", "paginacion": false, "mapping": {"documento": "pedido", "id_tercero": "cliente", "id_sucursal_cli": "sucursal_cliente", "fecha": "fecha_pedido", "referencia_item": "producto", "cant_pedida": "cantidad_pedida", "Precio_unit": "precio_unitario", "notas": "observacion", "co": "zona"}, "hardcodes": {"estado": "draft", "impuesto": 19.0, "almacen": 1}, "conditionals": [], "warehouse_mapping": {}}'::jsonb, NULL, true, 11, 1);

-- nota_credito (execution_order=12)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebackt'), 'nota_credito', 'purchases', '{"query_desc": "pinturastitopabon_Nota_Credito", "parametros": "FechaInicio = 20260101|FechaFin = 20261231", "paginacion": false, "mapping": {"Tercero": "proveedor", "Sucursal": "sucursal_proveedor", "Fecha": "fecha_entrega", "ConsecDocto": "referencia_compra", "referenciaItem": "producto", "cantidad": "cantidad", "Precio_unit": "precio_unitario", "Id_Bodega": "bodega_siesa"}, "hardcodes": {"estado": "draft", "impuesto": 19.0, "almacen": 1}, "conditionals": [{"tipo": "funcion", "campo_destino": "compra", "funcion": "concatenar_campos", "params": {"campos": ["Co", "TipoDocto", "ConsecDocto"], "separador": "-"}}], "warehouse_mapping": {}}'::jsonb, NULL, true, 12, 1);

-- transferencia_entrada (execution_order=13)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebackt'), 'transferencia_entrada', 'purchases', '{"query_desc": "pinturastitopabon_Transferencias_Entradas_Salidas", "parametros": "TipoDocto = TEM|FechaInicio = 20260101|FechaFin = 20261231", "paginacion": false, "mapping": {"ConsecDocto": "referencia_compra", "Referencia": "producto", "Cantidad": "cantidad", "Precio_unit": "precio_unitario", "BodegaEntrada": "bodega_siesa", "fecha": "fecha_entrega"}, "hardcodes": {"proveedor": "830075451", "sucursal_proveedor": "001", "estado": "draft", "impuesto": 19.0, "almacen": 1}, "conditionals": [{"tipo": "funcion", "campo_destino": "compra", "funcion": "concatenar_campos", "params": {"campos": ["CO", "TipoDocto", "ConsecDocto"], "separador": ""}}], "warehouse_mapping": {}}'::jsonb, NULL, true, 13, 1);

-- devolucion_out (execution_order=14)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebackt'), 'devolucion_out', 'sales', '{"query_desc": "pinturastitopabon_Salida_Inventario", "parametros": "FechaInicio = 20260101|FechaFin = 20261231", "paginacion": false, "mapping": {"Documento": "pedido", "Nit_Tercero": "cliente", "Sucursal": "sucursal_cliente", "Fecha": "fecha_pedido", "Referencia_Item": "producto", "Cantidad": "cantidad_pedida", "Precio_unit": "precio_unitario", "Notas": "observacion", "zona": "zona"}, "hardcodes": {"estado": "draft", "impuesto": 19.0, "almacen": 1, "vendedor": "", "condicion_pago": ""}, "conditionals": [], "warehouse_mapping": {}}'::jsonb, NULL, true, 14, 1);

-- transferencia_salida (execution_order=15)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebackt'), 'transferencia_salida', 'sales', '{"query_desc": "pinturastitopabon_Transferencias_Entradas_Salidas", "parametros": "TipoDocto = TSP|FechaInicio = 20260101|FechaFin = 20261231", "paginacion": false, "mapping": {"Referencia": "producto", "Cantidad": "cantidad_pedida", "Precio_unit": "precio_unitario", "BodegaSalida": "bodega_siesa", "BodegaEntrada": "zona"}, "hardcodes": {"cliente": "830075451", "sucursal_cliente": "001", "estado": "draft", "impuesto": 19.0, "almacen": 1, "observacion": "", "vendedor": "", "condicion_pago": ""}, "conditionals": [{"tipo": "funcion", "campo_destino": "pedido", "funcion": "concatenar_campos", "params": {"campos": ["CO", "TipoDocto", "ConsecDocto"], "separador": ""}}], "warehouse_mapping": {}}'::jsonb, NULL, true, 15, 1);

-- ============================================================
-- FLOWS — PRUEBASAP (9 flows)
-- ============================================================

-- items (execution_order=1)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebasap'), 'items', 'items', '{"endpoint": "Items", "filter": "Valid eq ''tYES'' and UpdateDate ge ''2026-07-01''", "mapping": {"ItemCode": "referencia", "ItemName": "descripcion", "BarCode": "codigo_barras", "U_FB_EANWMS": "codigos_extras", "ItemsGroupCode_resolved": "categoria", "ProdStdCost": "costo", "InventoryUOM": "unidad", "SalesUnitWeight": "peso", "SalesUnitVolume": "volumen"}, "hardcodes": {"precio": 0, "impuesto": 0}, "conditionals": [{"tipo": "funcion", "campo_destino": "tracking", "funcion": "valor_por_lista", "params": {"campo_origen": "ItemsGroupCode", "lista": [307,313,315,316,317,304,320,321,322,323,329,332,331,333,334,318,309,314,319,305,330,308,324,337,340,306,339,341,342,344,345,346,347,349,352,351,350], "si": "lot", "no": "none"}}, {"tipo": "funcion", "campo_destino": "ruta", "funcion": "valor_por_campo", "params": {"campo_origen": "PurchaseItem", "valor": "tYES", "si": "Buy", "no": "Fabricar"}}, {"tipo": "funcion", "campo_destino": "type", "funcion": "valor_por_campo", "params": {"campo_origen": "InventoryItem", "valor": "tYES", "si": "product", "no": "consu"}}, {"tipo": "funcion", "campo_destino": "sap_field", "funcion": "sap_field_combined", "params": {"campo1": "U_FB_EnviarWMS", "campo2": "U_FB_EnviarProdWMS", "valor_esperado": "Y", "texto_ambos": "Producto Terminado, Produccion", "texto_solo_uno": "Producto Terminado"}}], "uom_mapping": {"UND": "Unidades", "und": "Unidades", "UNID": "Unidades", "KG": "kg", "LT": "lt", "MT": "m", "None": "Unidades"}, "resolve_filter_field": "ItemCode", "resolve_filter_template": "ItemCode eq ''{ref}''"}'::jsonb, NULL, true, 1, 1);

-- customer (execution_order=2)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebasap'), 'partners', 'customer', '{"endpoint": "BusinessPartners", "filter": "CardType eq ''cCustomer'' and UpdateDate ge ''2026-07-01''", "mapping": {"CardCode": "identificacion", "CardName": "nombre", "EmailAddress": "email", "Phone1": "telefono", "Phone2": "celular"}, "mapping_lineas": {"origen": "BPAddresses", "campos": {"AddressName": "sucursal", "Street": "direccion", "ZipCode": "codigo_postal", "City": "ciudad", "U_Zona": "zona"}}, "hardcodes": {"departamento": "", "pais": "Colombia"}, "conditionals": [], "sucursal_hierarchy": false, "country_id": 49, "identification_type_id": 5, "resolve_filter_field": "CardCode", "resolve_filter_template": "CardCode eq ''{ref}''"}'::jsonb, NULL, true, 2, 1);

-- supplier (execution_order=3)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebasap'), 'partners', 'supplier', '{"endpoint": "BusinessPartners", "filter": "CardType eq ''cSupplier'' and UpdateDate ge ''2026-07-01''", "mapping": {"CardCode": "identificacion", "CardName": "nombre", "EmailAddress": "email", "Phone1": "telefono", "Phone2": "celular"}, "mapping_lineas": {"origen": "BPAddresses", "campos": {"AddressName": "sucursal", "Street": "direccion", "ZipCode": "codigo_postal", "City": "ciudad"}}, "hardcodes": {"departamento": "", "pais": "Colombia"}, "conditionals": [], "country_id": 49, "identification_type_id": 5, "resolve_filter_field": "CardCode", "resolve_filter_template": "CardCode eq ''{ref}''"}'::jsonb, NULL, true, 3, 1);

-- compras (execution_order=10)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebasap'), 'compras', 'purchases', '{"endpoint": "PurchaseOrders", "filter": "DocDate ge ''2026-07-01''", "mapping": {"CardCode": "proveedor", "DocDate": "fecha_entrega", "DocEntry": "referencia_compra"}, "mapping_lineas": {"origen": "DocumentLines", "campos": {"ItemCode": "producto", "Quantity": "cantidad", "UnitPrice": "precio_unitario", "WarehouseCode": "bodega_sap"}}, "hardcodes": {"sucursal_proveedor": "000", "estado": "draft", "impuesto": 19, "almacen": 1}, "conditionals": [{"tipo": "funcion", "campo_destino": "compra", "funcion": "doc_name_por_rango", "params": {"campo_origen": "DocNum", "rangos": {"1-10000000": "OCNAL"}, "separador": "-"}}], "warehouse_mapping": {}}'::jsonb, NULL, true, 10, 1);

-- ventas (execution_order=11)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebasap'), 'ventas', 'sales', '{"endpoint": "DeliveryNotes", "filter": "DocDate ge ''2026-07-01''", "mapping": {"CardCode": "cliente", "ShipToCode": "sucursal_cliente", "DocDate": "fecha_pedido", "Comments": "observacion"}, "mapping_lineas": {"origen": "DocumentLines", "campos": {"ItemCode": "producto", "Quantity": "cantidad_pedida", "UnitPrice": "precio_unitario", "WarehouseCode": "bodega_sap", "ItemDescription": "descripcion"}}, "hardcodes": {"estado": "draft", "impuesto": 0, "almacen": 1, "zona": "", "vendedor": "", "condicion_pago": ""}, "conditionals": [{"tipo": "funcion", "campo_destino": "pedido", "funcion": "doc_name_por_rango", "params": {"campo_origen": "DocNum", "rangos": {"1-10000000": "PVNAL"}, "separador": "-"}}], "warehouse_mapping": {}}'::jsonb, NULL, true, 11, 1);

-- entrada_mercancia (execution_order=12)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebasap'), 'entrada_mercancia', 'purchases', '{"endpoint": "InventoryGenEntries", "filter": "DocDate ge ''2026-07-01''", "mapping": {"CardCode": "proveedor", "DocDate": "fecha_entrega", "DocEntry": "referencia_compra"}, "mapping_lineas": {"origen": "DocumentLines", "campos": {"ItemCode": "producto", "Quantity": "cantidad", "UnitPrice": "precio_unitario", "WarehouseCode": "bodega_sap"}}, "hardcodes": {"sucursal_proveedor": "000", "estado": "draft", "impuesto": 19, "almacen": 1}, "conditionals": [{"tipo": "funcion", "campo_destino": "compra", "funcion": "concatenar_campos", "params": {"campos": ["Series", "DocNum"], "separador": "-"}}], "warehouse_mapping": {}}'::jsonb, NULL, true, 12, 1);

-- transferencia_entrada (execution_order=13)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebasap'), 'transferencia_entrada', 'purchases', '{"endpoint": "StockTransfers", "filter": "DocDate ge ''2026-07-01'' and ToWarehouse eq ''PRINCIP''", "mapping": {"CardCode": "proveedor", "DocDate": "fecha_entrega", "DocEntry": "referencia_compra"}, "mapping_lineas": {"origen": "StockTransferLines", "campos": {"ItemCode": "producto", "Quantity": "cantidad", "UnitPrice": "precio_unitario", "WarehouseCode": "bodega_sap"}}, "hardcodes": {"sucursal_proveedor": "000", "estado": "draft", "impuesto": 19, "almacen": 1}, "conditionals": [{"tipo": "funcion", "campo_destino": "compra", "funcion": "concatenar_campos", "params": {"campos": ["Series", "DocNum"], "separador": "-"}}], "warehouse_mapping": {}}'::jsonb, NULL, true, 13, 1);

-- salida_mercancia (execution_order=14)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebasap'), 'salida_mercancia', 'sales', '{"endpoint": "InventoryGenExits", "filter": "DocDate ge ''2026-07-01''", "mapping": {"CardCode": "cliente", "DocDate": "fecha_pedido", "Comments": "observacion"}, "mapping_lineas": {"origen": "DocumentLines", "campos": {"ItemCode": "producto", "Quantity": "cantidad_pedida", "UnitPrice": "precio_unitario", "WarehouseCode": "bodega_sap"}}, "hardcodes": {"sucursal_cliente": "000", "estado": "draft", "impuesto": 0, "almacen": 1, "zona": "", "vendedor": "", "condicion_pago": ""}, "conditionals": [{"tipo": "funcion", "campo_destino": "pedido", "funcion": "concatenar_campos", "params": {"campos": ["Series", "DocNum"], "separador": "-"}}], "warehouse_mapping": {}}'::jsonb, NULL, true, 14, 1);

-- transferencia_salida (execution_order=15)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebasap'), 'transferencia_salida', 'sales', '{"endpoint": "StockTransfers", "filter": "DocDate ge ''2026-07-01'' and FromWarehouse eq ''PRINCIP''", "mapping": {"CardCode": "cliente", "DocDate": "fecha_pedido", "Comments": "observacion"}, "mapping_lineas": {"origen": "StockTransferLines", "campos": {"ItemCode": "producto", "Quantity": "cantidad_pedida", "UnitPrice": "precio_unitario", "WarehouseCode": "bodega_sap"}}, "hardcodes": {"sucursal_cliente": "000", "estado": "draft", "impuesto": 0, "almacen": 1, "zona": "", "vendedor": "", "condicion_pago": ""}, "conditionals": [{"tipo": "funcion", "campo_destino": "pedido", "funcion": "concatenar_campos", "params": {"campos": ["Series", "DocNum"], "separador": "-"}}], "warehouse_mapping": {}}'::jsonb, NULL, true, 15, 1);

-- ============================================================
-- FLOWS — PRUEBAEXCEL (3 flows)
-- ============================================================

-- items (execution_order=1)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebaexcel'), 'items', 'items', '{"endpoint": "productos", "uom_mapping": {"UND": "Unidades", "und": "Unidades", "KG": "kg"}}'::jsonb, NULL, true, 1, 1);

-- customer (execution_order=2)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebaexcel'), 'partners', 'customer', '{"endpoint": "partners", "sucursal_hierarchy": false, "country_id": 49, "identification_type_id": 5}'::jsonb, NULL, true, 2, 1);

-- supplier (execution_order=3)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebaexcel'), 'partners', 'supplier', '{"endpoint": "partners", "country_id": 49, "identification_type_id": 5}'::jsonb, NULL, true, 3, 1);

-- compras (execution_order=10)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebaexcel'), 'compras', 'purchases', '{"endpoint": "entradas", "warehouse_mapping": {}}'::jsonb, NULL, true, 10, 1);

-- ventas (execution_order=11)
INSERT INTO flows (client_id, flow_name, flow_type, flow_config, schedule_cron, is_active, execution_order, created_by) VALUES ((SELECT id FROM clients WHERE client_id = 'pruebaexcel'), 'ventas', 'sales', '{"endpoint": "salidas", "warehouse_mapping": {}}'::jsonb, NULL, true, 11, 1);

-- ============================================================
-- Verificación
-- ============================================================
SELECT c.client_id, c.erp_type, COUNT(f.id) AS flows
FROM clients c
LEFT JOIN flows f ON f.client_id = c.id
WHERE c.client_id IN ('pruebaws','pruebackt','pruebasap','pruebaexcel')
GROUP BY c.client_id, c.erp_type
ORDER BY c.client_id;
